---
title: "PB-DOM"
author: "SimLac"
date: "2026-01-23"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set up}

library(tidyverse)
library(purrr)
library(sf)

rm(list = ls())

source("functions/utilities.R")
source("functions/load_chain.R")

```
## Simulation study

```{r get simulation parameters}

params <- data.frame(scenario = paste0("Scenario", 1:4),
                     alpha_psi = NA,
                     alpha_omega = logit(0.33), alpha_rho = logit(0.66), alpha = 7.5,
                     sigma = c(12.5,25,12.5,25),
                     alpha_gam = logit(0.5),
                     beta_gam = c(0,0,5,5))

sim_paths <- list.files("simulation_study/out", full.names = TRUE)[1:5] %>%
  map(list.dirs, full.names = TRUE, recursive = FALSE) %>%
  reduce(c)

simulation_summary <- strsplit(sim_paths, "/") %>%
  map(~.x[c(3,4)]) %>% 
  reduce(rbind) %>%
  data.frame 

colnames(simulation_summary) <- c("sim", "scenario")
simulation_summary <- simulation_summary %>%
  group_by(sim, scenario) %>%
  summarize(thr = paste0(2:4, ".sigma")) %>%
  left_join(params, by = "scenario") %>%
  pivot_longer(cols = sort(colnames(params)[-1]), names_to = "param", values_to = "true")
  

```

```{r check convergence}
# list.files(sim_paths, full.names = TRUE, pattern = "MCMC")[1:12] %>%
#   map(readRDS) %>%
#   walk(MCMCvis::MCMCtrace, pdf = FALSE, ind = TRUE, Rhat = TRUE)
```


```{r load chains}

simulation_summary <- list.files(sim_paths, full.names = TRUE, pattern = "MCMC") %>% 
  map(readRDS) %>%
  map(reduce, rbind) %>% 
  map(apply, 2, my_quantile) %>%
  map(t) %>%
  reduce(rbind) %>%
  cbind(simulation_summary, .)

```

```{r plot 95 CI}

ggplot(simulation_summary) +
  geom_pointrange(aes(x=med, xmin = inf, xmax = sup, y = thr, group = sim),
                  position = position_dodge(width = 1)) +
  geom_vline(aes(xintercept = true), linetype = "dashed", color = "red") +
  facet_grid(scenario ~ param, scales = "free") +
  xlab("") + ylab("") +
  theme_bw() +
  theme(text = element_text(face = "bold"),
        strip.placement = "outside",
        strip.background = element_blank())
```

## Case studies

```{r get data}

to_scale <- c("riverLength","ripForest", "waterBodyArea", "ibd","slope", 
              "Urban", "ArableCropland","HeterogeneousAgriculture")

effort  <- readRDS("wolf_case_study/data/effort_louvrier.rds")
wolfCovs <- readRDS("wolf_case_study/data/envcov_louvrier.rds")
  
bg <- read_sf("otter_case_study/data/background_grid.gpkg") %>%
  filter(cellArea >= 3.33e07) %>%
  mutate_if(is.numeric, ~ replace_na(.x, 0)) %>% 
  mutate(across(all_of(c("ANG", "CYP", "ECR", "SAL", "waterBodyArea", "Urban")),
                ~ truncate_to_quantile(sqrt(.x), 0.95))) %>%
  mutate(across(all_of(to_scale), ~ c(scale(.x)))) %>%
  arrange(id)

```

```{r set up case study analysis}

species_to_plot <- c("otter")

chains <- list(wolf = c(808831, 472213),
               otter = c(256545, 754774))

chains <- map2(c(wolf = "wolf_case_study/out/CHAIN_", otter = "otter_case_study/out/CHAIN_"),
               chains, paste0, "/")

colonization_covs <- list(wolf =  c("p_forest", "p_agri", "p_alti","p_halt", "p_dbarr", "p_rock"),
                          otter = c("riverLength","ripForest", "waterBodyArea",
                                    "ibd","slope", "ArableCropland",
                                    "HeterogeneousAgriculture"))

detection_covs <- list(wolf = c("effort", "p_road"),
                       otter.opport = c("year","Urban", "coastProx"),
                       otter.stdzed = c("year","Urban", "coastProx"))

X <- list(wolf = wolfCovs,
          otter = apply(as.matrix(st_drop_geometry(bg[,colonization_covs$otter])), 2, as.numeric)) 

X_det <- list(wolf = as.matrix(data.frame(effort = c(min(effort), max(effort)),
                                          p_road = c(min(X$wolf[, "p_road"]), max(X$wolf[, "p_road"])))),
              otter.opport = as.matrix(data.frame(year = c(-11,12),
                                                  Urban = c(min(bg$Urban), max(bg$Urban)),
                                                  coastProx = c(0,1))),
              otter.stdzed = as.matrix(data.frame(year = c(-11,12),
                                                  Urban = c(min(bg$Urban), max(bg$Urban)),
                                                  coastProx = c(0,1))))

dims <- list(wolf = c(N = dim(X$wolf)[1], T = 23),
             otter = c(N = dim(X$otter)[1], T = 6))

chains <- chains[species_to_plot]
dims <- dims[species_to_plot]

colonization_covs <- colonization_covs[species_to_plot]
detection_covs <- detection_covs[grepl(paste(species_to_plot, collapse = "|"), names(X_det))]
X <- X[species_to_plot]
X_det <- X_det[grepl(paste(species_to_plot, collapse = "|"), names(X_det))]

```

```{r load and inspect chains}

fit <- map2(chains, dims, ~ map(.x, load_chain , N = .y[1], T = .y[2]))

pars <- map(fit, ~ map(.x, "pars"))
zm <- map(fit, ~ map(.x, "zm"))

rm(fit)

walk(pars, MCMCvis::MCMCtrace, pdf = FALSE, ind = TRUE, Rhat = TRUE)

```

```{r collapse chains}

pars <- map(pars, reduce, rbind)
zm <- map(zm, reduce, function(.x, .y){(.x + .y)/ 2})

```


```{r dispersion kernel}

seq_d <- seq(0,50,1)
  
sigma <- map(pars, ~ .x[, "sigma"])

alpha <- map(pars, ~ .x[, "alpha"])

kerns <- map2(alpha, sigma, ~ map2(.x, .y, delta, x = seq_d)) %>%
  map(reduce, rbind) %>% 
  map(apply, 2, my_quantile) %>%
  imap(~ data.frame(species = .y, d = seq_d, t(.x))) %>%
  reduce(rbind)

ggplot(kerns) + 
  geom_line(aes(x = d, y = med, col = species), linewidth = .5) +
  geom_ribbon(aes(x = d, ymin = inf, ymax = sup, fill = species), alpha = 0.33) +
  xlab("d") + ylab("delta")+
  theme_bw()

```
```{r ksi}

ksi <- map(pars, ~.x[, grepl("ksi\\[", colnames(.x))]) %>%
  map2(names(X), ~ mutate(data.frame(.x), species = .y))

colnames(ksi$wolf)[1:(length(colonization_covs$wolf))] <- colonization_covs$wolf
colnames(ksi$otter)[1:(length(colonization_covs$otter))] <- colonization_covs$otter

ksi <- map2(ksi, colonization_covs, pivot_longer, names_to = "cov", values_to = "ksi") %>%
  map(group_by, species, cov) %>%
  map(summarize, p_accept = mean(ksi)) %>%
  reduce(rbind)

ggplot(ksi) + 
  geom_col(aes(x = cov, y = p_accept, fill = species)) +
  theme_bw() + 
  facet_wrap(~species, scale = "free_x")
```


```{r colonization}

alpha_gam <- map(pars, ~ .x[, "alpha_gam"])

beta_gam <- map(pars, ~ .x[, grepl("beta_gam\\[", colnames(.x))])

colonization_summary <- map(names(X),
                            ~ predict_over_all(X[[.x]], alpha_gam[[.x]],
                                               beta_gam[[.x]], colonization_covs[[.x]])) %>%
  map2(names(X), ~ mutate(.x, species = .y)) %>%
  reduce(rbind)

true_vals <- map2(X, colonization_covs,
                  ~ pivot_longer(data.frame(.x[, .y]), cols = all_of(.y),
                                 names_to = "cov", values_to = "x")) %>%
  reduce(rbind)
  
ggplot(colonization_summary) + 
  geom_line(aes(x = x, y = med, col = species), linewidth = .5) + 
  geom_ribbon(aes(x = x, ymin = inf, ymax = sup, fill = species), alpha = 0.5) + 
  geom_segment(data = true_vals, aes(x = x, xend = x, y = 0, yend = -Inf)) +
  facet_wrap(~ factor(cov, levels = reduce(colonization_covs, c)),
             scales = "free_x", nrow = 4) + 
  xlab("Scaled covariate value") + ylab("gamma")+
  theme_bw()

```

```{r detection}
alpha_rho <- list()
if("wolf" %in% species_to_plot) alpha_rho <- append(alpha_rho, list(wolf = pars$wolf[, "alpha_rho"]))
if("otter" %in% species_to_plot) alpha_rho <- append(alpha_rho,
                                                     list(otter.opport = pars$otter[, "alpha_rho[1]"],
                                                          otter.stdzed = pars$otter[, "alpha_rho[2]"]))

beta_rho <- list()
if("wolf" %in% species_to_plot) beta_rho <- append(beta_rho,
                                                   list(wolf = pars$wolf[, grepl("beta_rho\\[", colnames(pars$wolf))]))
if("otter" %in% species_to_plot) beta_rho <- append(beta_rho,
                                                     list(otter.opport = pars$otter[, c("beta_rho_t[1]",
                                                                                        "beta_rho[1, 1]", "beta_rho[1, 2]")],
                                                          otter.stdzed = pars$otter[, c("beta_rho_t[2]",
                                                                                        "beta_rho[2, 1]","beta_rho[2, 2]")]))
detection_summary <- map(names(X_det),
                            ~ predict_over_all(X_det[[.x]], alpha_rho[[.x]],
                                               beta_rho[[.x]], detection_covs[[.x]])) %>%
  map2(names(X_det), ~ mutate(.x, species = .y)) %>%
  reduce(rbind)

true_vals <- rbind(# data.frame(cov = "effort", x = c(effort)),
                   # data.frame(cov = "p_road", x = X$wolf[, "p_road"]),
                   data.frame(cov = "year", x = -11:12),
                   data.frame(cov = "Urban", x = bg$Urban))

ggplot(detection_summary) + 
  geom_line(aes(x = x, y = med, col = species), linewidth = .5) + 
  geom_ribbon(aes(x = x, ymin = inf, ymax = sup, fill = species), alpha = 0.5) + 
  geom_segment(data = true_vals, aes(x = x, xend = x, y = 0, yend = -Inf)) +
  facet_wrap(~ cov,
             scales = "free_x") + 
  xlab("Scaled covariate value") + ylab("gamma")+
  theme_bw()

```

```{r occu maps wolf}

france  <- filter(read_sf("wolf_case_study/data/countries_shp/"), NAME == "France")
xy      <- select(readRDS("wolf_case_study/data/coordcells_wolf.rds"), X, Y)

zm.df <- cbind(xy, t(zm$wolf))
colnames(zm.df) <- c("X", "Y", paste0("t", 1:23))
zm.df <- pivot_longer(zm.df, cols = all_of(paste0("t", 1:23)),
                      names_to = "t", values_to = "psi") %>%
  mutate(t = as.numeric(gsub("t", "", t)))

plot_t <- c(1, 4, 9, 12, 15, 18, 21, 23)
ggplot(zm.df %>% filter(t %in% plot_t)) + 
  geom_tile(aes(x = X, y = Y, fill = psi), show.legend = F) + 
  geom_sf(data = france, fill = NA) +
  scale_fill_gradient(low = "lightgrey", high = "orange4") +
  facet_wrap(~ (t + 1995), nrow = 2) +
  xlab("") + ylab("") +
  theme_minimal()

```

```{r occu maps otters}

zm.df <- cbind(select(bg), t(zm$otter))
colnames(zm.df)[1:6] <- paste0("t", 1:6)

zm.df <- pivot_longer(zm.df, cols = all_of(paste0("t", 1:6)),
                      names_to = "t", values_to = "psi") %>%
  mutate(t = as.numeric(gsub("t", "", t)))

ggplot(zm.df) + 
  geom_sf(aes(fill = psi), show.legend = F, col = NA) + 
  scale_fill_gradient(low = "lightgrey", high = "orange4") +
  facet_wrap(~ (t), nrow = 2) +
  xlab("") + ylab("") +
  theme_minimal()

```

```{r col_map otter}

gamma <- map(species_to_plot, 
             ~ c(t(apply(invlogit(cbind(alpha_gam[[.x]], beta_gam[[.x]]) %*% t(cbind(1, X[[.x]][, colonization_covs[[.x]]]))), 2, mean))))

xy$gamma <- gamma[[1]]
bg$gamma <- gamma[[2]]

ggplot(bg) + 
  geom_sf(aes(fill = gamma), col = NA) + 
  paletteer::scale_fill_paletteer_c("grDevices::Viridis")+
  theme_minimal()

ggplot(xy) + 
  geom_tile(aes(x = X, y = Y, fill = gamma)) + 
  geom_sf(data = france, fill = NA) +
  paletteer::scale_fill_paletteer_c("grDevices::Viridis")+
  theme_minimal()
```

```{r plot random covariates }

xy$cc <- effort[,23]

ggplot(xy) + 
  geom_tile(aes(x = X, y = Y, fill = cc)) + 
  geom_sf(data = france, fill = NA) +
  paletteer::scale_fill_paletteer_c("grDevices::Viridis")+
  theme_minimal()

```

